/***************************************************************************
 *
 * osal-rs
 * Copyright (C) 2026 Antonio Salsi <passy.linux@zresa.it>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <https://www.gnu.org/licenses/>.
 *
 ***************************************************************************/

//! POSIX type definitions and handle wrappers.
//!
//! This module provides type aliases and handle types that interface with the
//! POSIX threading API (pthreads). Types are generated at build time based on
//! the detected target architecture's native word size.
//!
//! # Generated Types
//!
//! The following types are generated by the build script, based on the host
//! architecture reported by `uname`:
//!
//! - `TickType` - System tick counter type (`u32` on 32-bit, `u64` on 64-bit)
//! - `BaseType` - Basic signed integer type for return values
//! - `UBaseType` - Basic unsigned integer type
//! - `StackType` - Type used for stack allocation
//!
//! # Handle Types
//!
//! POSIX OS objects are referenced through opaque pointers (handles):
//!
//! - `ThreadHandle` - References a pthread
//! - `QueueHandle` - References a message queue
//! - `SemaphoreHandle` - References a semaphore
//! - `MutexHandle` - References a mutex
//! - `EventGroupHandle` - References an event group
//! - `TimerHandle` - References a timer

// Include build-time generated types based on the target architecture.
// This file is generated by the build script and contains:
// - TickType: System tick counter type
// - BaseType: Basic signed integer type
// - UBaseType: Basic unsigned integer type
// - StackType: Stack allocation type
include!(concat!(env!("OUT_DIR"), "/types_generated.rs"));

use core::ffi::{ c_ulong, c_void };
use core::fmt::Debug;

use crate::posix::ffi::{pthread_cond_t, pthread_mutex_t};

/// POSIX opaque handle types for OS primitives.
///
/// These handles are opaque pointers used to reference POSIX/pthread-backed
/// objects. They should not be dereferenced directly; instead, use the safe
/// wrappers provided by this crate (e.g., `Thread`, `Queue`, `Semaphore`, etc.).


/// Opaque POSIX thread identifier (`pthread_t`).
///
/// glibc defines `pthread_t` as `unsigned long int`, so `c_ulong` has the
/// correct size/representation on every target this crate builds for.

#[derive(Default)]
pub struct ClockMonotonicHandle (
    pub(in crate::posix) pthread_mutex_t, 
    pub(in crate::posix) pthread_cond_t,
);

impl Debug for ClockMonotonicHandle {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("ClockMonotonicHandle")
            .field("handle", &(&raw const self).addr())
            .finish()
    }
}

impl ClockMonotonicHandle {
    pub fn is_empty(&self) -> bool {
        self.0.is_empty() && self.1.is_empty() 
    }
}

pub type ThreadHandle = c_ulong;
pub type QueueHandle = *const c_void;
pub type SemaphoreHandle = ClockMonotonicHandle;
pub type EventGroupHandle = ClockMonotonicHandle;
pub type TimerHandle = *const c_void;
pub type MutexHandle = pthread_mutex_t;

/// Type alias for event group bits.
///
/// Represents a set of event flags where each bit can be set or cleared
/// independently. The underlying type is `TickType`, matching the native
/// word size of the target architecture.
pub type EventBits = TickType;