/***************************************************************************
 *
 * osal-rs
 * Copyright (C) 2026 Antonio Salsi <passy.linux@zresa.it>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <https://www.gnu.org/licenses/>.
 *
 ***************************************************************************/
#![cfg_attr(target_os = "none", no_std)]

//! Build-time utilities for `osal-rs`'s `build.rs`.
//!
//! [`TypeGenerator`] detects the active backend's `TickType`/`UBaseType`/
//! `BaseType`/`StackType` sizes and writes them as Rust type aliases into
//! `OUT_DIR/types_generated.rs` (included by `osal-rs` via `include!`),
//! wires up `cargo:rerun-if-changed` for the C porting sources, and - for
//! the `posix` backend - compiles and statically links the C porting layer.
//!
//! Exactly one of the `posix` or `freertos` features is expected to be
//! enabled, matching whichever backend `osal-rs` itself is being built with.

use std::env;

use std::path::PathBuf;
use std::convert::AsRef;
use std::ffi::OsStr;
use std::fs;
use std::process::Command;

/// Detects the active backend's platform type sizes and (for `posix`) links
/// the C porting layer, driven from a `build.rs` script.
///
/// Wraps the build script's `OUT_DIR` (where generated files are written)
/// and a flag recording whether the `real_time` (`SCHED_FIFO`) cfg should be
/// enabled for the crate being built.
///
/// # Examples
///
/// ```
/// use std::path::PathBuf;
///
/// // Cargo sets `OUT_DIR` automatically inside a real build script; set it
/// // by hand here so the example can run standalone. The path passed in
/// // needs at least two components (as `CARGO_MANIFEST_DIR` always has)
/// // since the `freertos` backend walks up two parents to find the
/// // workspace root.
/// unsafe { std::env::set_var("OUT_DIR", std::env::temp_dir()); }
///
/// let _generator = osal_rs_build::TypeGenerator::new(PathBuf::from("workspace/osal-rs"));
/// ```
pub struct TypeGenerator(PathBuf, bool);

impl TypeGenerator {
    /// Create a new generator with a custom FreeRTOSConfig.h path
    pub fn new<P>(manifest_path: P) -> Self
    where P: Into<PathBuf> + AsRef<OsStr>
    {
        #[cfg(feature = "posix")]
        {
            //Avoid unused_variables
            let _ = manifest_path;
        }

        #[cfg(feature = "freertos")]
        {
            // Initialize the type generator with the FreeRTOS configuration file path.
            // This will parse FreeRTOSConfig.h and generate Rust type definitions and constants.

            let manifest_path: PathBuf = manifest_path.into();

            let workspace_root = manifest_path
                .parent() // Go up to osal-rs/
                .and_then(|p| p.parent()) // Go up to workspace root
                .expect("Failed to find workspace root");


            // Determine the path to FreeRTOSConfig.h.
            // Priority: Environment variable > Default location
            let _freertos_config = if let Ok(config_path) = env::var("FREERTOS_CONFIG_PATH") {
                // Use the path specified in FREERTOS_CONFIG_PATH environment variable
                PathBuf::from(config_path)
            } else {
                // Default: Look for FreeRTOSConfig.h in <workspace_root>/inc/
                workspace_root.join("inc/FreeRTOSConfig.h")
            };
        }

        let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
        Self (
            out_dir, false
        )
    }


    /// Write the generated types to a file
    #[allow(dead_code)]
    fn write_generated_types(
        &self,
        tick_size: u16,
        tick_type: &str,
        u_base_size: u16,
        u_base_type: &str,
        base_size: u16,
        base_type: &str,
        stack_size: u16,
        stack_type: &str,
    ) {
        let generated_code = format!(r#"
// Auto-generated by build.rs - DO NOT EDIT MANUALLY
// This file contains FreeRTOS type mappings based on the actual type sizes

// FreeRTOS type mappings (auto-detected)
// TickType_t: {} bytes -> {}
// UBaseType_t: {} bytes -> {}
// BaseType_t: {} bytes -> {}
// StackType_t: {} bytes -> {}

/// Alias for the platform's tick-count type, sized to match `TickType_t` as detected at build time.
pub type TickType = {};
/// Alias for the platform's unsigned base type, sized to match `UBaseType_t` as detected at build time.
pub type UBaseType = {};
/// Alias for the platform's signed base type, sized to match `BaseType_t` as detected at build time.
pub type BaseType = {};
/// Alias for the platform's stack-element type, sized to match `StackType_t` as detected at build time.
pub type StackType = {};

"#,
            tick_size, tick_type,
            u_base_size, u_base_type,
            base_size, base_type,
            stack_size, stack_type,
            tick_type,
            u_base_type,
            base_type,
            stack_type
        );
        
        let types_rs = self.0.join("types_generated.rs");
        fs::write(&types_rs, generated_code).expect("Failed to write generated types");
    }

    /// Convert a size to the corresponding Rust type
    #[allow(unused)]
    fn size_to_type(size: u16, signed: bool) -> &'static str {
        match (size, signed) {
            (1, false) => "u8",
            (1, true) => "i8",
            (2, false) => "u16",
            (2, true) => "i16",
            (4, false) => "u32",
            (4, true) => "i32",
            (8, false) => "u64",
            (8, true) => "i64",
            // Default to u32 for unknown sizes
            _ => if signed { "i32" } else { "u32" },
        }
    }

    /// Enable the `sched_fifo` feature cfg for the crate build when requested.
    #[allow(unused)]
    fn enable_sched_fifo(&self) {
        if self.1 {
            println!("cargo:rustc-cfg=feature=\"real_time\"");
        }
    }

}


#[cfg(feature = "posix")]
impl TypeGenerator {

    /// Tells Cargo to re-run the build script when the POSIX C porting
    /// sources change.
    ///
    /// # Examples
    ///
    /// ```
    /// osal_rs_build::TypeGenerator::add_rerun_if_changed();
    /// ```
    pub fn add_rerun_if_changed() {
        println!("cargo:rerun-if-changed=../osal-rs-porting/posix/src/osal_rs.c");
        println!("cargo:rerun-if-changed=../osal-rs-porting/posix/inc/osal_rs.h");
    }

    /// Probes the host architecture (and `SCHED_FIFO` support) by compiling
    /// and running a small C program with `gcc`, then writes the
    /// corresponding `TickType`/`UBaseType`/`BaseType`/`StackType` aliases
    /// into `OUT_DIR/types_generated.rs`.
    ///
    /// # Examples
    ///
    /// ```
    /// use std::path::PathBuf;
    ///
    /// unsafe { std::env::set_var("OUT_DIR", std::env::temp_dir()); }
    /// let mut generator = osal_rs_build::TypeGenerator::new(PathBuf::from("Cargo.toml"));
    /// generator.generate_types();
    ///
    /// assert!(std::env::temp_dir().join("types_generated.rs").exists());
    /// ```
    pub fn generate_types(&mut self) {

        let query_program = r#"
#include <stdio.h>
#include <sys/utsname.h>

int main() {
    struct utsname buffer;
    if (uname(&buffer) == 0) {
        printf("ARCH=%s\n", buffer.machine);
    }
#if defined(USE_SCHED_FIFO)
    printf("SCHED_FIFO=1\n");
#else
    printf("SCHED_FIFO=0\n");
#endif
    return 0;
}
"#;

        let query_c = self.0.join("query_types.c");
        fs::write(&query_c, query_program).expect("Failed to write query program");
        
        // Compile the query program
        let query_exe = self.0.join("query_types");
        let compile_status = Command::new("gcc")
            .arg(&query_c)
            .arg("-o")
            .arg(&query_exe)
            .status();
        
        if compile_status.is_ok() && compile_status.unwrap().success() {
            // Run the query program
            let output = Command::new(&query_exe)
                .output()
                .expect("Failed to run query program");
            
            let stdout = String::from_utf8_lossy(&output.stdout);


            for line in stdout.lines() {
                //println!("cargo:warning=line:{line}");
                if let Some(arch) = line.strip_prefix("ARCH=") {
                    match arch {
                        "x86_64" | "aarch64" | "riscv64" => {
                            // 64-bit architectures: native word size is 8 bytes
                            let tick_size: u16 = 8;
                            let u_base_size: u16 = 8;
                            let base_size: u16 = 8;
                            let base_signed = true;
                            let stack_size: u16 = 8;

                            let tick_type = Self::size_to_type(tick_size, false);
                            let u_base_type = Self::size_to_type(u_base_size, false);
                            let base_type = Self::size_to_type(base_size, base_signed);
                            let stack_type = Self::size_to_type(stack_size, true);

                            self.write_generated_types(tick_size, tick_type, u_base_size, u_base_type, base_size, base_type, stack_size, stack_type);
                        }
                        "x86" | "arm" | "riscv32" => {
                            // 32-bit architectures: native word size is 4 bytes
                            let tick_size: u16 = 4;
                            let u_base_size: u16 = 4;
                            let base_size: u16 = 4;
                            let base_signed = true;
                            let stack_size: u16 = 4;

                            let tick_type = Self::size_to_type(tick_size, false);
                            let u_base_type = Self::size_to_type(u_base_size, false);
                            let base_type = Self::size_to_type(base_size, base_signed);
                            let stack_type = Self::size_to_type(stack_size, true);

                            self.write_generated_types(tick_size, tick_type, u_base_size, u_base_type, base_size, base_type, stack_size, stack_type);
                        }
                        //TODO: mac
                        //TODO: freebsd
                        other => panic!("osal-rs-build: unsupported POSIX architecture '{other}'"),
                    }
                } else if let Some(value) = line.strip_prefix("SCHED_FIFO=") {
                    self.1 = value == "1";
                }
            }

        } else {
 

        }

    }

    /// Compile the POSIX porting C source (osal_rs.c) and archive it into a
    /// static library, then instruct cargo to link it into the crate.
    pub fn compile_sources(&self) {
        let src = "../osal-rs-porting/posix/src/osal_rs.c";
        let inc_dir = "../osal-rs-porting/posix/inc";

        let obj = self.0.join("osal_rs.o");
        let compile_status = Command::new("gcc")
            .arg("-c")
            .arg(src)
            .arg("-I")
            .arg(inc_dir)
            .arg("-o")
            .arg(&obj)
            .status()
            .expect("Failed to invoke gcc to compile osal_rs.c");

        if !compile_status.success() {
            panic!("osal-rs-build: failed to compile {src}");
        }

        let lib = self.0.join("libosal_rs_posix.a");
        let archive_status = Command::new("ar")
            .arg("crs")
            .arg(&lib)
            .arg(&obj)
            .status()
            .expect("Failed to invoke ar to archive osal_rs.o");

        if !archive_status.success() {
            panic!("osal-rs-build: failed to archive osal_rs.o into libosal_rs_posix.a");
        }

        println!("cargo:rustc-link-search=native={}", self.0.display());
        println!("cargo:rustc-link-lib=static=osal_rs_posix");
    }

    /// Runs the full POSIX build step: [`TypeGenerator::generate_types`],
    /// then [`TypeGenerator::compile_sources`] to build and link the C
    /// porting layer.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use std::path::PathBuf;
    ///
    /// // `compile_sources` shells out to `gcc`/`ar` and expects the C porting
    /// // sources at a path relative to the crate invoking the build script,
    /// // so this is illustrative rather than runnable standalone.
    /// unsafe { std::env::set_var("OUT_DIR", std::env::temp_dir()); }
    /// let mut generator = osal_rs_build::TypeGenerator::new(PathBuf::from("Cargo.toml"));
    /// generator.generate_all();
    /// ```
    pub fn generate_all(&mut self) {
        self.generate_types();
        self.enable_sched_fifo();
        self.compile_sources();
    }
}


#[cfg(feature = "freertos")]
impl TypeGenerator {


    /// Tells Cargo to re-run the build script when the FreeRTOS C porting
    /// sources change.
    ///
    /// # Examples
    ///
    /// ```
    /// osal_rs_build::TypeGenerator::add_rerun_if_changed();
    /// ```
    pub fn add_rerun_if_changed() {
        println!("cargo:rerun-if-changed=../osal-rs-porting/freeretos/src/osal_rs.c");
        println!("cargo:rerun-if-changed=../osal-rs-porting/freeretos/inc/osal_rs.h");
    }

    /// Query FreeRTOS type sizes and generate Rust type mappings
    pub fn generate_types(&mut self) {
        let (tick_size, ubase_size, base_size, base_signed, stack_size) = self.query_type_sizes();

        let tick_type = Self::size_to_type(tick_size, false);
        let ubase_type = Self::size_to_type(ubase_size, false);
        let base_type = Self::size_to_type(base_size, base_signed);
        let stack_type = Self::size_to_type(stack_size, true);


        self.write_generated_types(tick_size, tick_type, ubase_size, ubase_type, base_size, base_type, stack_size, stack_type);

        println!("cargo:warning=Generated FreeRTOS types: TickType={}, UBaseType={}, BaseType={} StackType={}",
                 tick_type, ubase_type, base_type, stack_type);
    }

    /// Generate both types and config
    #[inline]
    pub fn generate_all(&mut self) {
        self.generate_types();
        self.enable_sched_fifo();
        // self.generate_config();
    }

    /// Query the sizes of FreeRTOS types
    fn query_type_sizes(&mut self) -> (u16, u16, u16, bool, u16) {
        // Create a small C program to query the type sizes
        let query_program = r#"
#include <stdio.h>
#include <stdint.h>

// We need to include FreeRTOS headers - path will be provided by the main build
// For now, we'll use the compiled library approach
// This is a placeholder - we'll use the already compiled C library

int main() {
    // Since we can't easily compile against FreeRTOS in the build script,
    // we'll use a different approach: parse the compile_commands.json or
    // use predefined types based on common configurations

    // Common FreeRTOS configurations:
    // TickType_t is usually uint32_t (4 bytes) on 32-bit systems
    // UBaseType_t is usually uint32_t (4 bytes) on 32-bit systems
    // BaseType_t is usually int32_t (4 bytes) on 32-bit systems
    // StackType_t is usually long (4 bytes) on 32-bit systems

    printf("TICK_TYPE_SIZE=%d\n", 4);
    printf("UBASE_TYPE_SIZE=%d\n", 4);
    printf("BASE_TYPE_SIZE=%d\n", 4);
    printf("BASE_TYPE_SIGNED=1\n");
    printf("STACK_TYPE_SIZE=%d\n", 4);
    return 0;
}
"#;

        let query_c = self.0.join("query_types.c");
        fs::write(&query_c, query_program).expect("Failed to write query program");

        // Compile the query program
        let query_exe = self.0.join("query_types");
        let compile_status = Command::new("gcc")
            .arg(&query_c)
            .arg("-o")
            .arg(&query_exe)
            .status();

        if compile_status.is_ok() && compile_status.unwrap().success() {
            // Run the query program
            let output = Command::new(&query_exe)
                .output()
                .expect("Failed to run query program");

            let stdout = String::from_utf8_lossy(&output.stdout);
            let mut tick_size = 4u16;
            let mut ubase_size = 4u16;
            let mut base_size = 4u16;
            let mut base_signed = true;
            let mut stack_type = 4u16;

            for line in stdout.lines() {
                if let Some(val) = line.strip_prefix("TICK_TYPE_SIZE=") {
                    tick_size = val.parse().unwrap_or(4);
                } else if let Some(val) = line.strip_prefix("UBASE_TYPE_SIZE=") {
                    ubase_size = val.parse().unwrap_or(4);
                } else if let Some(val) = line.strip_prefix("BASE_TYPE_SIZE=") {
                    base_size = val.parse().unwrap_or(4);
                } else if let Some(val) = line.strip_prefix("BASE_TYPE_SIGNED=") {
                    base_signed = val.parse::<u8>().unwrap_or(1) == 1;
                } else if let Some(val) = line.strip_prefix("STACK_TYPE_SIZE=") {
                    stack_type = val.parse().unwrap_or(4);
                }
            }

            (tick_size, ubase_size, base_size, base_signed, stack_type)
        } else {
            // Default values for 32-bit ARM Cortex-M (typical for Raspberry Pi Pico)
            (4, 4, 4, true, 4)
        }
    }
}

